# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: SSH@0
  inputs:
    sshEndpoint: 'hususer@52.170.131.174'
    runOptions: 'commands'
    commands: 'ls /home'
    readyTimeout: '20000'



- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'test_test1.py'



- script: |
    python -m pip install --upgrade pip
    pyhthon3 -m venv test102
    source test102/bin/activate
    pip3 install -r requirements.txt
    pip3 list
    deactivate
    pip3 list
  displayName: 'edit Env'
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'hususer@52.170.131.174'
    contents: 'requirements.txt'
    targetFolder: '/home/hususer'
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    sshEndpoint: 'hususer@52.170.131.174'
    runOptions: 'commands'
    commands: |
      sudo apt-get install python3-venv
      sudo apt-get install python3-pip
      python3 -m venv test102
      source test102/bin/activate
      pip3 install -r requirements.txt
      pip  list --format=legacy
    readyTimeout: '20000'